# Generated by Django 5.1.4 on 2025-10-15 17:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0001_initial"),
        ("portfolios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioHolding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount invested in ILS",
                        max_digits=12,
                        verbose_name="investment amount",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="added at"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about this holding",
                        verbose_name="notes",
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_holdings",
                        to="funds.fund",
                        verbose_name="fund",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="portfolios.portfolio",
                        verbose_name="portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name": "portfolio holding",
                "verbose_name_plural": "portfolio holdings",
                "ordering": ["-added_at"],
                "indexes": [
                    models.Index(
                        fields=["portfolio", "-added_at"],
                        name="portfolios__portfol_10d8b8_idx",
                    )
                ],
                "unique_together": {("portfolio", "fund")},
            },
        ),
    ]
