# Generated by Django 5.1.4 on 2025-10-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0002_portfolioholding"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                help_text="Date of birth of the portfolio owner",
                null=True,
                verbose_name="date of birth",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                default="M",
                help_text="Gender of the portfolio owner",
                max_length=1,
                verbose_name="gender",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="owner_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Full name of the portfolio owner",
                max_length=200,
                verbose_name="owner name",
            ),
        ),
    ]
