# Generated by Django 5.1.4 on 2025-10-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0003_portfolio_date_of_birth_portfolio_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="legal_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Legal ID number (required to share with agents)",
                max_length=20,
                verbose_name="legal ID",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "גבר"), ("F", "נקבה")],
                default="M",
                help_text="Gender of the portfolio owner",
                max_length=1,
                verbose_name="gender",
            ),
        ),
    ]
