# Generated by Django 5.1.4 on 2025-10-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0004_portfolio_legal_id_alter_portfolio_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioholding",
            name="purchase_date",
            field=models.DateField(
                blank=True,
                help_text="Date when the fund was purchased",
                null=True,
                verbose_name="purchase date",
            ),
        ),
    ]
