# Generated by Django 5.1.4 on 2025-10-24 13:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0005_portfolioholding_purchase_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodicContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount to contribute each period (in ILS)",
                        max_digits=12,
                        verbose_name="contribution amount",
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("DAILY", "יומי"),
                            ("WEEKLY", "שבועי"),
                            ("MONTHLY", "חודשי"),
                            ("QUARTERLY", "רבעוני"),
                            ("YEARLY", "שנתי"),
                        ],
                        default="MONTHLY",
                        help_text="How often to contribute",
                        max_length=20,
                        verbose_name="contribution interval",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="When to start the periodic contributions",
                        verbose_name="start date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="When to end the periodic contributions (leave blank for indefinite)",
                        null=True,
                        verbose_name="end date",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this contribution plan is active",
                        verbose_name="is active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about this contribution plan",
                        verbose_name="notes",
                    ),
                ),
                (
                    "holding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periodic_contributions",
                        to="portfolios.portfolioholding",
                        verbose_name="holding",
                    ),
                ),
            ],
            options={
                "verbose_name": "periodic contribution",
                "verbose_name_plural": "periodic contributions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["holding", "is_active"],
                        name="portfolios__holding_148477_idx",
                    )
                ],
            },
        ),
    ]
