# Generated by Django 5.1.4 on 2025-10-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_contactrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentPreOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="last name"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="phone"),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="company"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="message")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "agent pre-order",
                "verbose_name_plural": "agent pre-orders",
                "ordering": ["-created_at"],
            },
        ),
    ]
