# Generated by Django 5.1.4 on 2025-10-24 16:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_agentpreorder"),
        ("portfolios", "0006_periodiccontribution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contactrequest",
            name="message",
            field=models.TextField(
                blank=True,
                help_text="Optional message from the user",
                verbose_name="message",
            ),
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "ממתין"),
                    ("ACCEPTED", "התקבל על ידי יועץ"),
                    ("ANSWERED", "טופל"),
                ],
                default="PENDING",
                help_text="Current status of the request",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.CreateModel(
            name="ContactRequestPortfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legal_id",
                    models.CharField(
                        help_text="Legal ID number shared for this portfolio",
                        max_length=20,
                        verbose_name="legal ID",
                    ),
                ),
                (
                    "contact_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_items",
                        to="core.contactrequest",
                        verbose_name="contact request",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolios.portfolio",
                        verbose_name="portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name": "contact request portfolio",
                "verbose_name_plural": "contact request portfolios",
            },
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="portfolios",
            field=models.ManyToManyField(
                related_name="contact_requests",
                through="core.ContactRequestPortfolio",
                to="portfolios.portfolio",
                verbose_name="portfolios",
            ),
        ),
        migrations.AddIndex(
            model_name="contactrequest",
            index=models.Index(
                fields=["user", "status", "-created_at"],
                name="core_contac_user_id_8c8c01_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contactrequestportfolio",
            unique_together={("contact_request", "portfolio")},
        ),
    ]
