# Generated by Django 5.1.4 on 2025-10-15 17:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the mutual fund",
                        max_length=300,
                        verbose_name="fund name",
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        help_text="The fund management company",
                        max_length=200,
                        verbose_name="management company",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("STOCKS", "מניות"),
                            ("BONDS", 'אג"ח'),
                            ("MIXED", "מעורב"),
                            ("MONEY_MARKET", "שוק כסף"),
                            ("FOREIGN", 'חו"ל'),
                            ("INDEX", "מדד"),
                            ("REAL_ESTATE", 'נדל"ן'),
                        ],
                        help_text="Fund category/type",
                        max_length=50,
                        verbose_name="category",
                    ),
                ),
                (
                    "return_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual return rate in percentage",
                        max_digits=6,
                        verbose_name="annual return rate",
                    ),
                ),
                (
                    "fund_number",
                    models.CharField(
                        blank=True,
                        help_text="Official fund number",
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="fund number",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "fund",
                "verbose_name_plural": "funds",
                "ordering": ["-return_rate"],
                "indexes": [
                    models.Index(
                        fields=["company", "category"],
                        name="funds_fund_company_320eca_idx",
                    ),
                    models.Index(
                        fields=["return_rate"], name="funds_fund_return__f382a9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FundLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="liked at"
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="funds.fund",
                        verbose_name="fund",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_funds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "fund like",
                "verbose_name_plural": "fund likes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="funds_fundl_user_id_c414ec_idx",
                    )
                ],
                "unique_together": {("user", "fund")},
            },
        ),
    ]
