# Generated by Django 5.1.4 on 2025-10-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fund",
            name="fund_classification",
            field=models.CharField(
                blank=True,
                help_text="Official fund classification from Gemelnet",
                max_length=200,
                verbose_name="fund classification",
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="fund_id",
            field=models.CharField(
                blank=True,
                help_text="Official fund ID from Gemelnet",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="fund ID",
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="inception_date",
            field=models.DateField(
                blank=True,
                help_text="Fund inception date",
                null=True,
                verbose_name="inception date",
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="management_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average annual management fee percentage",
                max_digits=5,
                null=True,
                verbose_name="management fee",
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="monthly_yield",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monthly yield percentage",
                max_digits=6,
                null=True,
                verbose_name="monthly yield",
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="report_period",
            field=models.IntegerField(
                blank=True,
                help_text="Report period in YYYYMM format",
                null=True,
                verbose_name="report period",
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="specialization",
            field=models.CharField(
                blank=True,
                help_text="Fund specialization",
                max_length=200,
                verbose_name="specialization",
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="sub_specialization",
            field=models.CharField(
                blank=True,
                help_text="Fund sub-specialization",
                max_length=200,
                verbose_name="sub-specialization",
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="total_assets",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total assets under management in millions",
                max_digits=15,
                null=True,
                verbose_name="total assets",
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="ytd_yield",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Year to date yield percentage",
                max_digits=6,
                null=True,
                verbose_name="year to date yield",
            ),
        ),
        migrations.AlterField(
            model_name="fund",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STOCKS", "מניות"),
                    ("BONDS", 'אג"ח'),
                    ("MIXED", "מעורב"),
                    ("MONEY_MARKET", "שוק כסף"),
                    ("FOREIGN", 'חו"ל'),
                    ("INDEX", "מדד"),
                    ("REAL_ESTATE", 'נדל"ן'),
                ],
                help_text="Fund category/type",
                max_length=50,
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="fund",
            name="company",
            field=models.CharField(
                help_text="The fund management company",
                max_length=300,
                verbose_name="management company",
            ),
        ),
        migrations.AlterField(
            model_name="fund",
            name="fund_number",
            field=models.CharField(
                blank=True,
                help_text="Official fund number (legacy)",
                max_length=20,
                null=True,
                verbose_name="fund number",
            ),
        ),
        migrations.AlterField(
            model_name="fund",
            name="name",
            field=models.CharField(
                help_text="Full name of the mutual fund",
                max_length=500,
                verbose_name="fund name",
            ),
        ),
        migrations.AlterField(
            model_name="fund",
            name="return_rate",
            field=models.DecimalField(
                decimal_places=2,
                help_text="5-year average annual return rate in percentage",
                max_digits=6,
                verbose_name="annual return rate",
            ),
        ),
    ]
