# Generated by Django 5.1.4 on 2025-10-16 08:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0002_fund_fund_classification_fund_fund_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legal_id",
                    models.CharField(
                        help_text="Company legal identification number",
                        max_length=50,
                        unique=True,
                        verbose_name="legal ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the management company",
                        max_length=300,
                        verbose_name="company name",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "company",
                "verbose_name_plural": "companies",
                "ordering": ["name"],
            },
        ),
        migrations.RenameIndex(
            model_name="fund",
            new_name="funds_fund_company_5d92d7_idx",
            old_name="funds_fund_company_320eca_idx",
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["legal_id"], name="funds_compa_legal_i_ff676d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["name"], name="funds_compa_name_5cd465_idx"),
        ),
        migrations.AlterField(
            model_name="fund",
            name="company",
            field=models.ForeignKey(
                help_text="The fund management company",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funds",
                to="funds.company",
                verbose_name="management company",
            ),
        ),
    ]
