# Generated by Django 5.1.4 on 2025-10-16 08:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0003_company_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fund",
            name="monthly_yield",
        ),
        migrations.RemoveField(
            model_name="fund",
            name="report_period",
        ),
        migrations.RemoveField(
            model_name="fund",
            name="ytd_yield",
        ),
        migrations.AddField(
            model_name="fund",
            name="latest_report_period",
            field=models.IntegerField(
                blank=True,
                help_text="Latest report period available in YYYYMM format",
                null=True,
                verbose_name="latest report period",
            ),
        ),
        migrations.AlterField(
            model_name="fund",
            name="return_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Latest 5-year average annual return (cached from latest snapshot)",
                max_digits=6,
                null=True,
                verbose_name="latest return rate",
            ),
        ),
        migrations.AlterField(
            model_name="fund",
            name="total_assets",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Latest total assets (cached from latest snapshot)",
                max_digits=15,
                null=True,
                verbose_name="latest total assets",
            ),
        ),
        migrations.CreateModel(
            name="FundSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_period",
                    models.IntegerField(
                        help_text="Report period in YYYYMM format (e.g., 202508)",
                        verbose_name="report period",
                    ),
                ),
                (
                    "monthly_yield",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly yield percentage for this period",
                        max_digits=6,
                        null=True,
                        verbose_name="monthly yield",
                    ),
                ),
                (
                    "ytd_yield",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Year to date yield percentage",
                        max_digits=6,
                        null=True,
                        verbose_name="year to date yield",
                    ),
                ),
                (
                    "return_3yr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Trailing 3-year return percentage",
                        max_digits=6,
                        null=True,
                        verbose_name="3-year return",
                    ),
                ),
                (
                    "return_5yr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Trailing 5-year return percentage",
                        max_digits=6,
                        null=True,
                        verbose_name="5-year return",
                    ),
                ),
                (
                    "avg_annual_return_3yr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average annual return over 3 years",
                        max_digits=6,
                        null=True,
                        verbose_name="avg annual return 3yr",
                    ),
                ),
                (
                    "avg_annual_return_5yr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average annual return over 5 years",
                        max_digits=6,
                        null=True,
                        verbose_name="avg annual return 5yr",
                    ),
                ),
                (
                    "total_assets",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total assets under management in millions",
                        max_digits=15,
                        null=True,
                        verbose_name="total assets",
                    ),
                ),
                (
                    "deposits",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Deposits during this period in millions",
                        max_digits=12,
                        null=True,
                        verbose_name="deposits",
                    ),
                ),
                (
                    "withdrawals",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Withdrawals during this period in millions",
                        max_digits=12,
                        null=True,
                        verbose_name="withdrawals",
                    ),
                ),
                (
                    "net_deposits",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Net deposits (deposits - withdrawals) in millions",
                        max_digits=12,
                        null=True,
                        verbose_name="net deposits",
                    ),
                ),
                (
                    "standard_deviation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Standard deviation of returns",
                        max_digits=6,
                        null=True,
                        verbose_name="standard deviation",
                    ),
                ),
                (
                    "alpha",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Alpha coefficient",
                        max_digits=6,
                        null=True,
                        verbose_name="alpha",
                    ),
                ),
                (
                    "sharpe_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Sharpe ratio",
                        max_digits=6,
                        null=True,
                        verbose_name="sharpe ratio",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="funds.fund",
                        verbose_name="fund",
                    ),
                ),
            ],
            options={
                "verbose_name": "fund snapshot",
                "verbose_name_plural": "fund snapshots",
                "ordering": ["-report_period"],
                "indexes": [
                    models.Index(
                        fields=["fund", "-report_period"],
                        name="funds_funds_fund_id_45358c_idx",
                    ),
                    models.Index(
                        fields=["report_period"], name="funds_funds_report__49b003_idx"
                    ),
                ],
                "unique_together": {("fund", "report_period")},
            },
        ),
    ]
