# Generated by Django 5.1.4 on 2025-10-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0004_remove_fund_monthly_yield_remove_fund_report_period_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fund",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Fund category from Gemelnet FUND_CLASSIFICATION",
                max_length=200,
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="fund",
            name="fund_classification",
            field=models.CharField(
                blank=True,
                help_text="Official fund classification from Gemelnet (same as category)",
                max_length=200,
                verbose_name="fund classification",
            ),
        ),
    ]
