# Generated by Django 5.1.4 on 2025-10-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0005_alter_fund_category_alter_fund_fund_classification"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="short_name",
            field=models.CharField(
                blank=True,
                help_text="Short display name for the company",
                max_length=100,
                verbose_name="short company name",
            ),
        ),
    ]
