# Generated by Django 5.1.4 on 2025-10-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0006_company_short_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundsnapshot",
            name="avg_annual_management_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average annual management fee percentage",
                max_digits=5,
                null=True,
                verbose_name="avg annual management fee",
            ),
        ),
        migrations.AddField(
            model_name="fundsnapshot",
            name="avg_deposit_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average deposit fee percentage",
                max_digits=5,
                null=True,
                verbose_name="avg deposit fee",
            ),
        ),
        migrations.AddField(
            model_name="fundsnapshot",
            name="foreign_currency_exposure",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Foreign currency exposure in millions",
                max_digits=15,
                null=True,
                verbose_name="foreign currency exposure",
            ),
        ),
        migrations.AddField(
            model_name="fundsnapshot",
            name="foreign_exposure",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Foreign exposure in millions",
                max_digits=15,
                null=True,
                verbose_name="foreign exposure",
            ),
        ),
        migrations.AddField(
            model_name="fundsnapshot",
            name="internal_transfers",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Internal transfers in millions",
                max_digits=12,
                null=True,
                verbose_name="internal transfers",
            ),
        ),
        migrations.AddField(
            model_name="fundsnapshot",
            name="liquid_assets_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentage of liquid assets",
                max_digits=5,
                null=True,
                verbose_name="liquid assets percent",
            ),
        ),
        migrations.AddField(
            model_name="fundsnapshot",
            name="net_monthly_deposits",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Net monthly deposits in millions",
                max_digits=12,
                null=True,
                verbose_name="net monthly deposits",
            ),
        ),
        migrations.AddField(
            model_name="fundsnapshot",
            name="stock_market_exposure",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Stock market exposure in millions",
                max_digits=15,
                null=True,
                verbose_name="stock market exposure",
            ),
        ),
    ]
