# Generated by Django 5.1.4 on 2025-10-23 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="שם קטגוריה"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True, verbose_name="תיאור")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "קטגוריה",
                "verbose_name_plural": "קטגוריות",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="שם תגית"
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
            options={
                "verbose_name": "תגית",
                "verbose_name_plural": "תגיות",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="כותרת")),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("content", models.TextField(verbose_name="תוכן")),
                (
                    "excerpt",
                    models.TextField(blank=True, max_length=300, verbose_name="תקציר"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="תאריך יצירה"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="תאריך עדכון"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="פורסם"),
                ),
                ("views", models.PositiveIntegerField(default=0, verbose_name="צפיות")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="כותב",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="knowledge_center.category",
                        verbose_name="קטגוריה",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="articles",
                        to="knowledge_center.tag",
                        verbose_name="תגיות",
                    ),
                ),
            ],
            options={
                "verbose_name": "מאמר",
                "verbose_name_plural": "מאמרים",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="תוכן התגובה")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="תאריך יצירה"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="תאריך עדכון"),
                ),
                ("is_approved", models.BooleanField(default=True, verbose_name="אושר")),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="knowledge_center.article",
                        verbose_name="מאמר",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="כותב",
                    ),
                ),
            ],
            options={
                "verbose_name": "תגובה",
                "verbose_name_plural": "תגובות",
                "ordering": ["created_at"],
            },
        ),
    ]
