# Generated by Django 5.1.4 on 2025-10-23 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_center", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submitter_full_name",
                    models.CharField(max_length=200, verbose_name="שם מלא"),
                ),
                (
                    "expertise_type",
                    models.CharField(
                        choices=[
                            ("AGENT", "סוכן פיננסי"),
                            ("ADVISOR", "יועץ פיננסי"),
                            ("ACADEMIC", "אקדמאי"),
                            ("ANALYST", "אנליסט פיננסי"),
                            ("INVESTOR", "משקיע מנוסה"),
                            ("OTHER", "אחר"),
                        ],
                        max_length=20,
                        verbose_name="סוג מומחיות",
                    ),
                ),
                (
                    "agent_diploma_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="מספר רישיון סוכן"
                    ),
                ),
                (
                    "advisor_diploma_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="מספר רישיון יועץ"
                    ),
                ),
                (
                    "academic_institution",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="שם מוסד אקדמי"
                    ),
                ),
                (
                    "academic_degree",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BA", "תואר ראשון (BA/BSc)"),
                            ("MA", "תואר שני (MA/MSc)"),
                            ("MBA", "MBA"),
                            ("PHD", "דוקטורט (PhD)"),
                            ("MD", "רפואה (MD)"),
                            ("EDD", "חינוך (EdD)"),
                            ("JD", "משפטים (JD)"),
                        ],
                        max_length=10,
                        verbose_name="תואר אקדמי",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="כותרת")),
                (
                    "excerpt",
                    models.TextField(max_length=300, verbose_name="תקציר (2 שורות)"),
                ),
                ("content", models.TextField(verbose_name="תוכן")),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "ממתין לבדיקה"),
                            ("APPROVED", "אושר"),
                            ("DECLINED", "נדחה"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="סטטוס בדיקה",
                    ),
                ),
                (
                    "decline_reason",
                    models.TextField(blank=True, verbose_name="סיבת דחייה"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="תאריך הגשה"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="תאריך בדיקה"
                    ),
                ),
                (
                    "approved_article",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submission",
                        to="knowledge_center.article",
                        verbose_name="מאמר שאושר",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="knowledge_center.category",
                        verbose_name="קטגוריה",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="מגיש",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="knowledge_center.tag", verbose_name="תגיות"
                    ),
                ),
            ],
            options={
                "verbose_name": "הגשת מאמר",
                "verbose_name_plural": "הגשות מאמרים",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
