# Generated by Django 5.1.4 on 2025-10-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_center", "0002_articlesubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlesubmission",
            name="company_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="שם חברה"),
        ),
        migrations.AddField(
            model_name="articlesubmission",
            name="other_expertise",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="מומחיות אחרת"
            ),
        ),
    ]
