# Generated by Django 5.1.4 on 2025-10-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_center", "0003_articlesubmission_company_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlesubmission",
            name="english_title",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="כותרת באנגלית"
            ),
        ),
    ]
