# Generated by Django 5.1.4 on 2025-10-26 07:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_center", "0004_articlesubmission_english_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=ckeditor.fields.RichTextField(verbose_name="תוכן"),
        ),
        migrations.AlterField(
            model_name="articlesubmission",
            name="content",
            field=ckeditor.fields.RichTextField(verbose_name="תוכן"),
        ),
    ]
